server:
  port: 9030
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb:// USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
        - id: resume-creation-service
          uri: lb:// RESUME-CREATION-SERVICE
          predicates:
            - Path=/api/v1/resumes/**
        - id: resume-upload-service
          uri: lb:// RESUME-UPLOAD-SERVICE
          predicates:
            - Path=/api/v2/resumes/**
