spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: payment-service

stripe:
  secretKey: sk_test_51RAVJcPdZcurC6UqMMuRbTOpFXOuig5SOv9nWrA4bTpcVfyeI9QaIXhrRU9veA6SEAFUzc4l2KOlSSxTngCWXJCF00rcjauBxc
  successUrl: http://localhost:8080/v1/webhook/transactions/
  cancelUrl: http://localhost:8080/v1/webhook/transactions/cancel/

