spring:
  application:
    name: Resume-service


    data:
      mongodb:
        uri:mongodb://localhost:27017/Reviewyme


server:
  port: 8033


  profiles:
    active: dev

---
spring:
  profiles: dev
file:
  upload-dir: /path/to/dev/upload/directory

---
spring:
  profiles: prod
file:
  upload-dir: /path/to/prod/upload/directory

